parameters:
  linux:
    network:
      interface:
        primary_first_nic:
          name: ${_param:primary_first_nic}
          enabled: true
          type: slave
          master: bond0
          mtu: 9000
          pre_up_cmds:
          - /sbin/ethtool --offload ${_param:primary_first_nic} rx off tx off tso off gro off
        primary_second_nic:
          name: ${_param:primary_second_nic}
          enabled: true
          type: slave
          master: bond0
          mtu: 9000
          pre_up_cmds:
          - /sbin/ethtool --offload ${_param:primary_second_nic} rx off tx off tso off gro off
        bond0:
          enabled: true
          proto: static
          type: bond
          address: ${_param:deploy_address}
          netmask: 255.255.255.192
          gateway: 172.17.11.1
          use_interfaces:
          - ${_param:primary_second_nic}
          - ${_param:primary_first_nic}
          slaves: ${_param:primary_second_nic} ${_param:primary_first_nic}
          mode: 802.3ad
          lacp_rate: 1
          mtu: 9000
        bond0.119:
          enabled: true
          type: vlan
          proto: static
          address: ${_param:control_address}
          netmask: 255.255.255.192
          mtu: 9000
          use_interfaces:
          - bond0
        bond0.120:
          enabled: true
          type: vlan
          proto: manual
          mtu: 9000
          use_interfaces:
          - bond0
        vhost0:
          enabled: true
          type: eth
          mtu: 9000
          address: ${_param:single_address}
          netmask: 255.255.255.192
          name_servers:
           - 8.8.8.8
          pre_up_cmds:
          - /usr/lib/contrail/if-vhost0
          use_interfaces:
          - bond0.120