classes:
  - service.libvirt.server.kvm
parameters:
  salt:
    control:
      enabled: True
      virt_enabled: True
      size:
        vm01.local:
          cpu: 32
          ram: 65536
          disk_profile: small
          net_profile: default
      cluster:
        internal:
          domain: ${_param:cluster_domain}
          engine: virt
          node:
            vm01:
              provider: kvm01.${_param:cluster_domain}
              image: ${_param:salt_control_trusty_image}
              size: vm01.local
  virt:
    nic:
      default:
        eth0:
          bridge: br0
          model: virtio
    disk:
      default:
        - system:
            size: 50000
      xxxsmall:
        - system:
            size: 8000
      xxsmall:
        - system:
            size: 15000
      xsmall:
        - system:
            size: 30000
      small:
        - system:
            size: 50000
      medium:
        - system:
            size: 80000
      large:
        - system:
            size: 100000
      xlarge:
        - system:
            size: 150000
      xxlarge:
        - system:
            size: 300000
      xxxlarge:
        - system:
            size: 500000
